export enum SPORT_TYPE {
  RUNNING = 'RUNNING',
  TRAIL_RUNNING = 'TRAIL_RUNNING',
  CYCLING = 'CYCLING',
  SWIMMING = 'SWIMMING',
  ROCK_CLIMBING = 'ROCK_CLIMBING',
  HIKING = 'HIKING',
  OTHER = 'OTHER',
}
